server:
  port: 8761
error:
  whitelabel:
    enabled: false
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchReistry: false
    serviceUrl:
      defultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
    
